datasource:
  mysql:
    url: jdbc:mysql://192.168.0.105/stc-wherehouse
    username: borge
    password: Develop/2022
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    dialect: org.hibernate.dialect.MySQL8Dialect
    showsql: true
server:
  port: 8086
spring:
  application:
    name: warehouse-service
  boot:
    admin:
      client:
        url: [ http://localhost:8081/admin-service ]
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com:
      bytesw: INFO
    springFramework:
      web:
        client:
          RestTemplate: INFO