server:
  port: 8083
spring:
  application:
    name: security-profile
  boot:
    admin:
      client:
        url: [ http://stc.service.discovery:8081/admin-service ]
eureka:
  client:
    service-url:
      defaultZone: http://stc.service.discovery:8081/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com:
      bytesw: INFO
    springFramework:
      web:
        client:
          RestTemplate: INFO
datasource:
  mysql:
    url: jdbc:mysql://stc-database:3306/security?autoReconect=true
    username: jjgonzalez
    password: Desarrollo.2022
    driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
      dialect: org.hibernate.dialect.MySQL8Dialect
      showSql: true